name: Github Actions Secret

on:
  push:
    branches: [ develop ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    steps:
      name: Step 1 - Echo out a Github Actions Secret to the logs
      run: |
        echo "The Github Action Secret will be masked: "
        echo ${{ secrets.REACT_APP_TOKEN }}
        echo "Trick to echo Github Action Secret: "
        echo ${{ secrets.REACT_APP_TOKEN }} | sed 's/./& /g'