name: Secrets
on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Test
        run: |
          if [ "$REACT_APP_TOKEN" == "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"]
          then
            echo "Got secret"
          fi
        env:
          REACT_APP_TOKEN: ${{ secrets.REACT_APP_TOKEN }}